name: deploy mamnonhoalu by ZUNO
on:
  push:
    branches: [main]
jobs:
  build:
    # if: ${{ github.event.pull_request.merged }}
    name: DEPLOY
    runs-on: ubuntu-latest
    steps:
      - name: checkout main branch
        uses: actions/checkout@v2

      - name: ssh to ubuntu server
        uses: appleboy/ssh-action@master
        with:
          host: 13.214.30.74
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          port: 22
          envs: GITHUB_RUN_NUMBER
          script: sh deploy.sh
          
